### PR TITLE
ensure typings is run for start; target case-sensitive in tsconfig.json

### PR DESCRIPTION
**Pull request by mikekidder**

### CODE REVIEW

**Comment by johnpapa** [comment]
we dont want to run typings before starting every time.

also need to keep this in synch with the A2 team's recommendation in their quickstart

**Comment by mikekidder** [comment]
Then I'd recommend either adding to documentation for here and quickstart:
 "npm run typings", or add it as a "postinstall".

The script should be ```"typings" : "typings install"``` for it to run though

Technically it runs, but users will see errors in the console output

**Comment by johnpapa** [comment]
its missing this ... want to PR it?

`    "postinstall": "npm run typings install",`

**Comment by johnpapa** [comment]
I just updated it

**Pull request closed without merging**
