### PR TITLE
Replace deprecated ng api

### LINKED ISSUE #14: replace deprecated api + tweak routing
You are using deprecated `bind` Api which is now `provide` with slightly different syntax. 
Also in docs, there is info that Path Location strategy is used which doesn't reflect the code. 

IMO the hash strategy would be better to use with live-server and also the user won't get confused when he reloads the page on some active route + the Note section can get shorter :)

### PR DESCRIPTION
**Pull request by Hotell**
closes #14

### CODE REVIEW

**Comment by johnpapa** [comment]
thanks. was in the process already

**Comment by Hotell** [comment]
actually there has been more than View removal. I just wanna help here.

**Comment by johnpapa** [comment]
sure. i recommend making individual PRs so I can accept one-offs.

provide is not working in the alpha i have, for the bootstrapping.

the readme comments might be nice, but id like to hear why too.

**Comment by Hotell** [comment]
hmm yeah makes sense to separate them.

provide is working 100% since version alpha39. there is different syntax in comparison with deprecated bind, which I've updated. 

So should I do another PR just with bind->provide refactor?

About that routing changes, I thought that explanation here will be enough, but I'm up to discussion, anyway, it's your repo :)
https://github.com/johnpapa/angular2-go/issues/14

thanks

**Comment by johnpapa** [comment]
sure, make the bind provide one again. it didn't work with the d.ts files for me

**Comment by Hotell** [comment]
will do

**Pull request closed without merging**
